Json convertermodel
it-kmitl-2018/group6 pull request #25
Opened 2018-04-07 18:24 UTC by pikepeak

ทำการสร้าง model สำหรับ Json Converter

2018-04-08 04:47 UTC, champillon reviewed
แก้มาหน่อยเน้อ ชี้แจงมาด้วย

2018-04-08 04:47 UTC, champillon commented on app/convertermodels/Json/Address.scala
> +package convertermodels.Json
ทำไมไม่เป็น converter.models.Json หล่ะ ไมเขียนชนกันเลย

2018-04-08 04:47 UTC, champillon commented on app/convertermodels/JsonMessage.scala
> +case class JsonMessage(seller: Seller, buyer: Buyer)
ไมตั้งชื่อว่า JsonMessage หล่ะ

2018-04-08 05:36 UTC, pikepeak commented on app/convertermodels/Json/Address.scala
> +package convertermodels.Json
ตอนนี้ผมเปลี่ยนชื่อ package ให้เเยกกันเเล้วครับ

2018-04-08 05:43 UTC, pikepeak commented on app/convertermodels/JsonMessage.scala
> +case class JsonMessage(seller: Seller, buyer: Buyer)
คือคิดว่าเป็น model สำหรับใช้ในการแปลงข้อมูลเป็น Json ที่จะส่งข้อมูลกลับไปหน้าบ้าน เลยคิดว่าใช้เป็น JsonMessage ถ้าไม่ชื่อไม่โอเค ช่วยเเนะนำหน่อยครับ ขอบคุณครับ

2018-04-08 05:45 UTC, champillon commented on app/convertermodels/JsonMessage.scala
> +case class JsonMessage(seller: Seller, buyer: Buyer)
TaxInvoice ดีกว่ามะ เพราะชื่อ package ก็บอกอยู่แล้วว่าเป็น converter ของ model ของ json

2018-04-08 06:03 UTC, pikepeak commented on app/convertermodels/JsonMessage.scala
> +case class JsonMessage(seller: Seller, buyer: Buyer)
ตอนนี้เเก้ชื่อเป็น TaxInvoice เเล้วครับ

2018-04-09 03:15 UTC, champillon approved these changes
LGTM la

2018-04-09 03:34 UTC, mahasak requested changes
No Test

2018-04-10 04:57 UTC, pikepeak commented
@mahasak ตอนนี้ผมทำ test มาเเล้วครับ ช่วย review ต่อที่ครับ ขอบคุณครับ

2018-04-10 07:50 UTC, champillon commented
รอพี่หมี ไปนะจร๊ะ @mahasak

2018-04-12 15:14 UTC, mahasak approved these changes
LGTM kub

2018-04-13 02:57 UTC, merged

2018-04-13 04:46 UTC, champillon commented
คะแนนครับ 3.5 คะแนน
5.1 การ design เป็น components เพื่อทำให้คนอื่นทำงานร่วมกันต่อได้ง่าย => 1 คะแนน
5.2 คุณภาพของการตั้งชื่อตัวแปร, ฟังก์ชั่น และความเรียบร้อยของ code => 0.5 คะแนน
5.3 ความยากเชิงเทคนิคที่นำมาประยุกต์ใช้ เช่น แปลง XML Schema เป็น Java code => 0 คะแนน
5.4 รายละเอียดการตั้งชื่อใน PR name และ commit log รวมทั้งรายละเอียดที่บรรยายใน issue ของ PR นั้นๆ => 1 คะแนน
5.5 ความสอดคล้องกันกับ PR อื่นๆของทีม ที่ทำงานร่วมกันได้ดี => 1 คะแนน